### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by fujinjun** [douchuan/jvm#7]
不确认是不是我自己的问题，在crates/vm/src/runtime/thread/condvar.rs 文件中 ：
line 51: use mem; => use std::mem;
line 92: use mem; => use std::mem;
line 113:mutex::raw=>mutex_raw
改完就可以运行了

**Comment by douchuan** [comment]
thanks,
the code not tested on other platform, my dev platform is Mac

caused by
#[cfg(not(any(
        target_os = "macos",
        target_os = "ios",
        target_os = "l4re",
        target_os = "android",
        target_os = "hermit"
    )))]

**Comment by douchuan** [comment]
pls make one pull request
